### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by rafinskipg** [substack/invoicer#8]
Hi , I've just installed invoicer but it didn't generate any config file on the default directory 

`~/.config/invoicer/`

I'm trying to force the prompter but it fails

```
invoicer -c 'config.json'

Cannot find module 'config.json'
at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/invoicer/bin/cmd.js:52:15)

```

Example config.json (could be added in the docs)
```
{
   "name" : "This is pepito",
   "address": "My address",
   "email": "my@email.com",
   "currency" : "€"
}
````

**Comment by rogeruiz** [comment]
:+1:
